spring.application.name=backend-mini-ecommerce-api

#Config H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Config connection
spring.datasource.url=jdbc:h2:mem:pos_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Config hibernate and sql init
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always